package edu.jhuapl.sbmt.model.image;

public enum ImageType
{
    MSI_IMAGE,
    AMICA_IMAGE,
    FC_IMAGE,
    FCCERES_IMAGE,
    PHOBOS_IMAGE,
    DEIMOS_IMAGE,
    OSIRIS_IMAGE,
    SATURN_MOON_IMAGE,
    SSI_GASPRA_IMAGE,
    SSI_IDA_IMAGE,
    MSI_MATHILDE_IMAGE,
    MVIC_JUPITER_IMAGE,
    LEISA_JUPITER_IMAGE,
    LORRI_IMAGE,
    POLYCAM_IMAGE,
    MAPCAM_IMAGE,
    POLYCAM_V4_IMAGE,
    MAPCAM_V4_IMAGE,
    HRIV_IMAGE,
    ITS_IMAGE,
    MRI_IMAGE,
    TEMPEL1_IMAGE,
    GENERIC_IMAGE,
    MAPCAM_EARTH_IMAGE,
    POLYCAM_EARTH_IMAGE,
    SAMCAM_EARTH_IMAGE
}